### ISSUE TITLE
make a release

### ISSUE THREAD

**Issue by till** [breerly/factory-girl-php#12]
A conservative 0.1.0 maybe?

**Comment by hanneskaeufler** [comment]
I think a release would be great as well! :+1:

**Comment by dincho** [comment]
:+1:

**Comment by fesor** [comment]
:+1:

**Comment by till** [comment]
@breerly @glaubinix I made a draft of a 1.0.0-alpha1 release. Let me know if you agree and I'll publish it.

**Comment by breerly** [comment]
:+1:

**Comment by glaubinix** [comment]
:+1:

**Comment by till** [comment]
:tada: :rocket:
